# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: utomatic-sync
version: "0.0.11"
slug: utomatic-sync
description: utomatic add-on for Home Assistant
url: "https://github.com/utomatic/ha-sync/tree/main/utomatic-sync"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  api_token: ''
  HOST: ''
schema:
  api_token: str
  host: str?
  log_level: list(debug|info|warning|error)?
image: "ghcr.io/utomatic/utomatic-sync-{arch}-addon"
