# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Espcloud-sync add-on
version: "0.0.6"
slug: espcloud-sync
description: Espcloud add-on for Home Assistant
url: "https://github.com/espcloud/ha-espcloud-sync/tree/main/espcloud-sync"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  api_token: ''
schema:
  api_token: str
  log_level: list(debug|info|warning|error)?
image: "ghcr.io/espcloud/espcloud-sync-{arch}-addon"
